name: dart_utilities
description: Minimal Technology Utilities
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.2

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
dependencies:
  collection: ^1.19.0
