name: df_utilities
description: Minimal Technology Utilities
version: 0.0.1
homepage: https://github.com/MINIMAL-TECHNOLOGY/dart_utilities
repository: https://github.com/MINIMAL-TECHNOLOGY/dart_utilities

environment:
  sdk: ^3.5.2

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
dependencies:
  collection: ^1.19.0
